import type { Metadata } from "next";
import Header2 from "./components/Header2";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Header2></Header2>
        {children}
<Footer></Footer>
      </body>
    </html>
  );
}
